---
- hosts: workstation

  tasks:
    - name: print from playbook
      debug: msg="in playbooks/homebrew.yml playbook"

    - name: install homebrew
      mac_pkg: pkg_type=script script_creates=/usr/local/bin/brew
               script_prefix='echo | ' script_exe=ruby
               url=https://raw.githubusercontent.com/Homebrew/install/master/install

    - name: install apps from homebrew
      homebrew: name={{item}} state=present
      with_items:
          - ack
          - ansible
          - coreutils
          - ctags
          - git
          - heroku-toolbelt
          - imagemagick
          - maven
          - openssl
          - postgresql
          - rbenv
          - redis
          - wget
          - youtube-dl
